# Generated by Django 3.1.2 on 2020-11-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
