# Generated by Django 3.1.2 on 2020-11-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0002_auto_20201103_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_path',
            new_name='path',
        ),
    ]
