# Generated by Django 3.1.2 on 2020-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0003_auto_20201103_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='path',
            new_name='image',
        ),
    ]
