# Generated by Django 3.1.2 on 2020-11-04 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0005_auto_20201103_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 18, 42, 43, 630114, tzinfo=utc)),
        ),
    ]
